
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2020.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2024 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xedgetracing_accel.h"

/*
* The configuration table for devices
*/

XEdgetracing_accel_Config XEdgetracing_accel_ConfigTable[XPAR_XEDGETRACING_ACCEL_NUM_INSTANCES] =
{
	{
		XPAR_EDGETRACING_ACCEL_0_DEVICE_ID,
		XPAR_EDGETRACING_ACCEL_0_S_AXI_CONTROL_BASEADDR
	}
};


