-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
-- Version: 2020.2
-- Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity canny_accel_xFPackNMS_11_11_800_1280_13_13_8_32_2_2_6_24_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    nms_mat_410_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    nms_mat_410_empty_n : IN STD_LOGIC;
    nms_mat_410_read : OUT STD_LOGIC;
    dst_mat_422_din : OUT STD_LOGIC_VECTOR (63 downto 0);
    dst_mat_422_full_n : IN STD_LOGIC;
    dst_mat_422_write : OUT STD_LOGIC;
    imgheight_dout : IN STD_LOGIC_VECTOR (9 downto 0);
    imgheight_empty_n : IN STD_LOGIC;
    imgheight_read : OUT STD_LOGIC;
    imgwidth_dout : IN STD_LOGIC_VECTOR (10 downto 0);
    imgwidth_empty_n : IN STD_LOGIC;
    imgwidth_read : OUT STD_LOGIC );
end;


architecture behav of canny_accel_xFPackNMS_11_11_800_1280_13_13_8_32_2_2_6_24_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (6 downto 0) := "0000010";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (6 downto 0) := "0000100";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (6 downto 0) := "0001000";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (6 downto 0) := "0010000";
    constant ap_ST_fsm_pp0_stage3 : STD_LOGIC_VECTOR (6 downto 0) := "0100000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv12_20 : STD_LOGIC_VECTOR (11 downto 0) := "000000100000";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv10_3 : STD_LOGIC_VECTOR (9 downto 0) := "0000000011";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal nms_mat_410_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal icmp_ln129_reg_502 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln139_reg_506 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_pp0_stage2 : BOOLEAN;
    signal icmp_ln139_1_reg_510 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage3 : signal is "none";
    signal ap_block_pp0_stage3 : BOOLEAN;
    signal icmp_ln139_2_reg_514 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal icmp_ln139_3_reg_518 : STD_LOGIC_VECTOR (0 downto 0);
    signal dst_mat_422_blk_n : STD_LOGIC;
    signal imgheight_blk_n : STD_LOGIC;
    signal imgwidth_blk_n : STD_LOGIC;
    signal j_reg_144 : STD_LOGIC_VECTOR (31 downto 0);
    signal imgheight_read_reg_470 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln116_fu_241_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln116_reg_475 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln117_fu_267_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln117_reg_483 : STD_LOGIC_VECTOR (9 downto 0);
    signal i_1_fu_271_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal i_1_reg_488 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln122_fu_277_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln129_fu_305_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln129_reg_497 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln129_fu_309_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state3_pp0_stage0_iter0 : BOOLEAN;
    signal ap_predicate_op82_read_state7 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln139_fu_314_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln139_1_fu_325_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln139_2_fu_336_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln139_3_fu_347_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_s_fu_355_p5 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_predicate_op63_read_state4 : BOOLEAN;
    signal ap_block_state4_pp0_stage1_iter0 : BOOLEAN;
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal p_Result_6_fu_367_p5 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_Result_8_fu_379_p5 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_predicate_op69_read_state5 : BOOLEAN;
    signal ap_block_state5_pp0_stage2_iter0 : BOOLEAN;
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal p_Result_7_fu_391_p5 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_Result_10_fu_403_p5 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_predicate_op75_read_state6 : BOOLEAN;
    signal ap_block_state6_pp0_stage3_iter0 : BOOLEAN;
    signal ap_block_pp0_stage3_11001 : BOOLEAN;
    signal p_Result_9_fu_415_p5 : STD_LOGIC_VECTOR (63 downto 0);
    signal j_1_fu_427_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal j_1_reg_552 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state3 : STD_LOGIC;
    signal ap_block_pp0_stage3_subdone : BOOLEAN;
    signal i_reg_133 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal ap_phi_mux_j_phi_fu_148_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter0_val_V_13_reg_156 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_phi_reg_pp0_iter0_val_V_14_reg_165 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_phi_reg_pp0_iter0_val_V_15_reg_174 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_phi_reg_pp0_iter1_val_V_15_reg_174 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_phi_mux_val_V_12_phi_fu_186_p4 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_Result_12_fu_433_p5 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_phi_reg_pp0_iter1_val_V_12_reg_183 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_Result_11_fu_446_p5 : STD_LOGIC_VECTOR (63 downto 0);
    signal val_V_fu_104 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal tmp_fu_197_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal and_ln_fu_207_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln110_fu_193_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln111_fu_215_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal col_loop_count_ac_fu_231_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln111_fu_225_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal icmp_ln111_fu_219_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_fu_245_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln111_1_fu_255_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal col_loop_count_fu_259_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln129_fu_282_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_20_fu_287_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_21_fu_297_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal or_ln139_fu_319_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln139_1_fu_330_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln139_2_fu_341_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_condition_493 : BOOLEAN;
    signal ap_condition_498 : BOOLEAN;
    signal ap_condition_225 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln122_fu_277_p2 = ap_const_lv1_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln122_fu_277_p2 = ap_const_lv1_0))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((((ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln122_fu_277_p2 = ap_const_lv1_0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter0_val_V_13_reg_156_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_493)) then
                if ((icmp_ln139_reg_506 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter0_val_V_13_reg_156 <= p_Result_6_fu_367_p5;
                elsif ((icmp_ln139_reg_506 = ap_const_lv1_0)) then 
                    ap_phi_reg_pp0_iter0_val_V_13_reg_156 <= p_Result_s_fu_355_p5;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter0_val_V_14_reg_165_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_498)) then
                if ((icmp_ln139_1_reg_510 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter0_val_V_14_reg_165 <= p_Result_7_fu_391_p5;
                elsif ((icmp_ln139_1_reg_510 = ap_const_lv1_0)) then 
                    ap_phi_reg_pp0_iter0_val_V_14_reg_165 <= p_Result_8_fu_379_p5;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_val_V_15_reg_174_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_225)) then
                if (((icmp_ln139_2_reg_514 = ap_const_lv1_1) and (icmp_ln129_reg_502 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter1_val_V_15_reg_174 <= p_Result_9_fu_415_p5;
                elsif (((icmp_ln139_2_reg_514 = ap_const_lv1_0) and (icmp_ln129_reg_502 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter1_val_V_15_reg_174 <= p_Result_10_fu_403_p5;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_val_V_15_reg_174 <= ap_phi_reg_pp0_iter0_val_V_15_reg_174;
                end if;
            end if; 
        end if;
    end process;

    i_reg_133_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                i_reg_133 <= i_1_reg_488;
            elsif ((not(((imgwidth_empty_n = ap_const_logic_0) or (imgheight_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_reg_133 <= ap_const_lv10_0;
            end if; 
        end if;
    end process;

    j_reg_144_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln129_reg_502 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                j_reg_144 <= j_1_reg_552;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln122_fu_277_p2 = ap_const_lv1_0))) then 
                j_reg_144 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                i_1_reg_488 <= i_1_fu_271_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln129_reg_502 <= icmp_ln129_fu_309_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln129_fu_309_p2 = ap_const_lv1_0))) then
                icmp_ln139_1_reg_510 <= icmp_ln139_1_fu_325_p2;
                icmp_ln139_2_reg_514 <= icmp_ln139_2_fu_336_p2;
                icmp_ln139_3_reg_518 <= icmp_ln139_3_fu_347_p2;
                icmp_ln139_reg_506 <= icmp_ln139_fu_314_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                imgheight_read_reg_470 <= imgheight_dout;
                    zext_ln116_reg_475(7 downto 0) <= zext_ln116_fu_241_p1(7 downto 0);
                    zext_ln117_reg_483(8 downto 0) <= zext_ln117_fu_267_p1(8 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln129_reg_502 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then
                j_1_reg_552 <= j_1_fu_427_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln129_reg_502 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then
                val_V_fu_104 <= ap_phi_mux_val_V_12_phi_fu_186_p4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln122_fu_277_p2 = ap_const_lv1_0))) then
                    zext_ln129_reg_497(9 downto 2) <= zext_ln129_fu_305_p1(9 downto 2);
            end if;
        end if;
    end process;
    zext_ln116_reg_475(31 downto 8) <= "000000000000000000000000";
    zext_ln117_reg_483(9) <= '0';
    zext_ln129_reg_497(1 downto 0) <= "00";
    zext_ln129_reg_497(31 downto 10) <= "0000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, imgheight_empty_n, imgwidth_empty_n, ap_enable_reg_pp0_iter0, ap_CS_fsm_state2, icmp_ln122_fu_277_p2, icmp_ln129_fu_309_p2, ap_block_pp0_stage0_subdone, ap_block_pp0_stage3_subdone, ap_block_pp0_stage1_subdone, ap_block_pp0_stage2_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((imgwidth_empty_n = ap_const_logic_0) or (imgheight_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln122_fu_277_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln129_fu_309_p2 = ap_const_lv1_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln129_fu_309_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when ap_ST_fsm_pp0_stage3 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                end if;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when others =>  
                ap_NS_fsm <= "XXXXXXX";
        end case;
    end process;
    add_ln111_fu_225_p2 <= std_logic_vector(unsigned(zext_ln111_fu_215_p1) + unsigned(ap_const_lv12_20));
    add_ln129_fu_282_p2 <= std_logic_vector(unsigned(zext_ln117_reg_483) + unsigned(ap_const_lv10_3));
    and_ln_fu_207_p3 <= (tmp_fu_197_p4 & ap_const_lv5_0);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(2);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(3);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(4);
    ap_CS_fsm_pp0_stage3 <= ap_CS_fsm(5);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state8 <= ap_CS_fsm(6);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(nms_mat_410_empty_n, dst_mat_422_full_n, icmp_ln129_reg_502, ap_enable_reg_pp0_iter1, ap_predicate_op82_read_state7)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((icmp_ln129_reg_502 = ap_const_lv1_0) and (dst_mat_422_full_n = ap_const_logic_0)) or ((nms_mat_410_empty_n = ap_const_logic_0) and (ap_predicate_op82_read_state7 = ap_const_boolean_1))));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(nms_mat_410_empty_n, dst_mat_422_full_n, icmp_ln129_reg_502, ap_enable_reg_pp0_iter1, ap_predicate_op82_read_state7)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((icmp_ln129_reg_502 = ap_const_lv1_0) and (dst_mat_422_full_n = ap_const_logic_0)) or ((nms_mat_410_empty_n = ap_const_logic_0) and (ap_predicate_op82_read_state7 = ap_const_boolean_1))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(nms_mat_410_empty_n, dst_mat_422_full_n, icmp_ln129_reg_502, ap_enable_reg_pp0_iter1, ap_predicate_op82_read_state7)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((icmp_ln129_reg_502 = ap_const_lv1_0) and (dst_mat_422_full_n = ap_const_logic_0)) or ((nms_mat_410_empty_n = ap_const_logic_0) and (ap_predicate_op82_read_state7 = ap_const_boolean_1))));
    end process;

        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_11001_assign_proc : process(nms_mat_410_empty_n, ap_enable_reg_pp0_iter0, ap_predicate_op63_read_state4)
    begin
                ap_block_pp0_stage1_11001 <= ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (nms_mat_410_empty_n = ap_const_logic_0) and (ap_predicate_op63_read_state4 = ap_const_boolean_1));
    end process;


    ap_block_pp0_stage1_subdone_assign_proc : process(nms_mat_410_empty_n, ap_enable_reg_pp0_iter0, ap_predicate_op63_read_state4)
    begin
                ap_block_pp0_stage1_subdone <= ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (nms_mat_410_empty_n = ap_const_logic_0) and (ap_predicate_op63_read_state4 = ap_const_boolean_1));
    end process;

        ap_block_pp0_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage2_11001_assign_proc : process(nms_mat_410_empty_n, ap_enable_reg_pp0_iter0, ap_predicate_op69_read_state5)
    begin
                ap_block_pp0_stage2_11001 <= ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (nms_mat_410_empty_n = ap_const_logic_0) and (ap_predicate_op69_read_state5 = ap_const_boolean_1));
    end process;


    ap_block_pp0_stage2_subdone_assign_proc : process(nms_mat_410_empty_n, ap_enable_reg_pp0_iter0, ap_predicate_op69_read_state5)
    begin
                ap_block_pp0_stage2_subdone <= ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (nms_mat_410_empty_n = ap_const_logic_0) and (ap_predicate_op69_read_state5 = ap_const_boolean_1));
    end process;

        ap_block_pp0_stage3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage3_11001_assign_proc : process(nms_mat_410_empty_n, ap_enable_reg_pp0_iter0, ap_predicate_op75_read_state6)
    begin
                ap_block_pp0_stage3_11001 <= ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (nms_mat_410_empty_n = ap_const_logic_0) and (ap_predicate_op75_read_state6 = ap_const_boolean_1));
    end process;


    ap_block_pp0_stage3_subdone_assign_proc : process(nms_mat_410_empty_n, ap_enable_reg_pp0_iter0, ap_predicate_op75_read_state6)
    begin
                ap_block_pp0_stage3_subdone <= ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (nms_mat_410_empty_n = ap_const_logic_0) and (ap_predicate_op75_read_state6 = ap_const_boolean_1));
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, imgheight_empty_n, imgwidth_empty_n)
    begin
                ap_block_state1 <= ((imgwidth_empty_n = ap_const_logic_0) or (imgheight_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;

        ap_block_state3_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state4_pp0_stage1_iter0_assign_proc : process(nms_mat_410_empty_n, ap_predicate_op63_read_state4)
    begin
                ap_block_state4_pp0_stage1_iter0 <= ((nms_mat_410_empty_n = ap_const_logic_0) and (ap_predicate_op63_read_state4 = ap_const_boolean_1));
    end process;


    ap_block_state5_pp0_stage2_iter0_assign_proc : process(nms_mat_410_empty_n, ap_predicate_op69_read_state5)
    begin
                ap_block_state5_pp0_stage2_iter0 <= ((nms_mat_410_empty_n = ap_const_logic_0) and (ap_predicate_op69_read_state5 = ap_const_boolean_1));
    end process;


    ap_block_state6_pp0_stage3_iter0_assign_proc : process(nms_mat_410_empty_n, ap_predicate_op75_read_state6)
    begin
                ap_block_state6_pp0_stage3_iter0 <= ((nms_mat_410_empty_n = ap_const_logic_0) and (ap_predicate_op75_read_state6 = ap_const_boolean_1));
    end process;


    ap_block_state7_pp0_stage0_iter1_assign_proc : process(nms_mat_410_empty_n, dst_mat_422_full_n, icmp_ln129_reg_502, ap_predicate_op82_read_state7)
    begin
                ap_block_state7_pp0_stage0_iter1 <= (((icmp_ln129_reg_502 = ap_const_lv1_0) and (dst_mat_422_full_n = ap_const_logic_0)) or ((nms_mat_410_empty_n = ap_const_logic_0) and (ap_predicate_op82_read_state7 = ap_const_boolean_1)));
    end process;


    ap_condition_225_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001)
    begin
                ap_condition_225 <= ((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3));
    end process;


    ap_condition_493_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0, icmp_ln129_reg_502, ap_block_pp0_stage1_11001)
    begin
                ap_condition_493 <= ((icmp_ln129_reg_502 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1));
    end process;


    ap_condition_498_assign_proc : process(ap_enable_reg_pp0_iter0, icmp_ln129_reg_502, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001)
    begin
                ap_condition_498 <= ((icmp_ln129_reg_502 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2));
    end process;


    ap_condition_pp0_exit_iter0_state3_assign_proc : process(icmp_ln129_fu_309_p2)
    begin
        if ((icmp_ln129_fu_309_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state3 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state3 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, icmp_ln122_fu_277_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln122_fu_277_p2 = ap_const_lv1_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_j_phi_fu_148_p4_assign_proc : process(icmp_ln129_reg_502, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, j_reg_144, j_1_reg_552)
    begin
        if (((icmp_ln129_reg_502 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
            ap_phi_mux_j_phi_fu_148_p4 <= j_1_reg_552;
        else 
            ap_phi_mux_j_phi_fu_148_p4 <= j_reg_144;
        end if; 
    end process;


    ap_phi_mux_val_V_12_phi_fu_186_p4_assign_proc : process(icmp_ln129_reg_502, icmp_ln139_3_reg_518, p_Result_12_fu_433_p5, ap_phi_reg_pp0_iter1_val_V_12_reg_183, p_Result_11_fu_446_p5)
    begin
        if ((icmp_ln129_reg_502 = ap_const_lv1_0)) then
            if ((icmp_ln139_3_reg_518 = ap_const_lv1_1)) then 
                ap_phi_mux_val_V_12_phi_fu_186_p4 <= p_Result_11_fu_446_p5;
            elsif ((icmp_ln139_3_reg_518 = ap_const_lv1_0)) then 
                ap_phi_mux_val_V_12_phi_fu_186_p4 <= p_Result_12_fu_433_p5;
            else 
                ap_phi_mux_val_V_12_phi_fu_186_p4 <= ap_phi_reg_pp0_iter1_val_V_12_reg_183;
            end if;
        else 
            ap_phi_mux_val_V_12_phi_fu_186_p4 <= ap_phi_reg_pp0_iter1_val_V_12_reg_183;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_val_V_15_reg_174 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter1_val_V_12_reg_183 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";

    ap_predicate_op63_read_state4_assign_proc : process(icmp_ln129_reg_502, icmp_ln139_reg_506)
    begin
                ap_predicate_op63_read_state4 <= ((icmp_ln139_reg_506 = ap_const_lv1_1) and (icmp_ln129_reg_502 = ap_const_lv1_0));
    end process;


    ap_predicate_op69_read_state5_assign_proc : process(icmp_ln129_reg_502, icmp_ln139_1_reg_510)
    begin
                ap_predicate_op69_read_state5 <= ((icmp_ln139_1_reg_510 = ap_const_lv1_1) and (icmp_ln129_reg_502 = ap_const_lv1_0));
    end process;


    ap_predicate_op75_read_state6_assign_proc : process(icmp_ln129_reg_502, icmp_ln139_2_reg_514)
    begin
                ap_predicate_op75_read_state6 <= ((icmp_ln139_2_reg_514 = ap_const_lv1_1) and (icmp_ln129_reg_502 = ap_const_lv1_0));
    end process;


    ap_predicate_op82_read_state7_assign_proc : process(icmp_ln129_reg_502, icmp_ln139_3_reg_518)
    begin
                ap_predicate_op82_read_state7 <= ((icmp_ln129_reg_502 = ap_const_lv1_0) and (icmp_ln139_3_reg_518 = ap_const_lv1_1));
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln122_fu_277_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln122_fu_277_p2 = ap_const_lv1_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    col_loop_count_ac_fu_231_p4 <= imgwidth_dout(10 downto 3);
    col_loop_count_fu_259_p3 <= 
        tmp_s_fu_245_p4 when (icmp_ln111_fu_219_p2(0) = '1') else 
        zext_ln111_1_fu_255_p1;

    dst_mat_422_blk_n_assign_proc : process(dst_mat_422_full_n, icmp_ln129_reg_502, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
        if (((icmp_ln129_reg_502 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
            dst_mat_422_blk_n <= dst_mat_422_full_n;
        else 
            dst_mat_422_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    dst_mat_422_din <= ap_phi_mux_val_V_12_phi_fu_186_p4;

    dst_mat_422_write_assign_proc : process(icmp_ln129_reg_502, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln129_reg_502 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
            dst_mat_422_write <= ap_const_logic_1;
        else 
            dst_mat_422_write <= ap_const_logic_0;
        end if; 
    end process;

    i_1_fu_271_p2 <= std_logic_vector(unsigned(i_reg_133) + unsigned(ap_const_lv10_1));
    icmp_ln111_fu_219_p2 <= "0" when (trunc_ln110_fu_193_p1 = ap_const_lv5_0) else "1";
    icmp_ln122_fu_277_p2 <= "1" when (i_reg_133 = imgheight_read_reg_470) else "0";
    icmp_ln129_fu_309_p2 <= "1" when (ap_phi_mux_j_phi_fu_148_p4 = zext_ln129_reg_497) else "0";
    icmp_ln139_1_fu_325_p2 <= "1" when (signed(or_ln139_fu_319_p2) < signed(zext_ln116_reg_475)) else "0";
    icmp_ln139_2_fu_336_p2 <= "1" when (signed(or_ln139_1_fu_330_p2) < signed(zext_ln116_reg_475)) else "0";
    icmp_ln139_3_fu_347_p2 <= "1" when (signed(or_ln139_2_fu_341_p2) < signed(zext_ln116_reg_475)) else "0";
    icmp_ln139_fu_314_p2 <= "1" when (signed(ap_phi_mux_j_phi_fu_148_p4) < signed(zext_ln116_reg_475)) else "0";

    imgheight_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, imgheight_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            imgheight_blk_n <= imgheight_empty_n;
        else 
            imgheight_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    imgheight_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, imgheight_empty_n, imgwidth_empty_n)
    begin
        if ((not(((imgwidth_empty_n = ap_const_logic_0) or (imgheight_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            imgheight_read <= ap_const_logic_1;
        else 
            imgheight_read <= ap_const_logic_0;
        end if; 
    end process;


    imgwidth_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, imgwidth_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            imgwidth_blk_n <= imgwidth_empty_n;
        else 
            imgwidth_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    imgwidth_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, imgheight_empty_n, imgwidth_empty_n)
    begin
        if ((not(((imgwidth_empty_n = ap_const_logic_0) or (imgheight_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            imgwidth_read <= ap_const_logic_1;
        else 
            imgwidth_read <= ap_const_logic_0;
        end if; 
    end process;

    j_1_fu_427_p2 <= std_logic_vector(unsigned(j_reg_144) + unsigned(ap_const_lv32_4));

    nms_mat_410_blk_n_assign_proc : process(nms_mat_410_empty_n, ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0, ap_block_pp0_stage1, icmp_ln129_reg_502, icmp_ln139_reg_506, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2, icmp_ln139_1_reg_510, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3, icmp_ln139_2_reg_514, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln139_3_reg_518)
    begin
        if ((((icmp_ln139_2_reg_514 = ap_const_lv1_1) and (icmp_ln129_reg_502 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((icmp_ln139_1_reg_510 = ap_const_lv1_1) and (icmp_ln129_reg_502 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((icmp_ln139_reg_506 = ap_const_lv1_1) and (icmp_ln129_reg_502 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((icmp_ln129_reg_502 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln139_3_reg_518 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)))) then 
            nms_mat_410_blk_n <= nms_mat_410_empty_n;
        else 
            nms_mat_410_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    nms_mat_410_read_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op82_read_state7, ap_block_pp0_stage0_11001, ap_predicate_op63_read_state4, ap_block_pp0_stage1_11001, ap_predicate_op69_read_state5, ap_block_pp0_stage2_11001, ap_predicate_op75_read_state6, ap_block_pp0_stage3_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_predicate_op75_read_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_predicate_op69_read_state5 = ap_const_boolean_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_predicate_op63_read_state4 = ap_const_boolean_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op82_read_state7 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)))) then 
            nms_mat_410_read <= ap_const_logic_1;
        else 
            nms_mat_410_read <= ap_const_logic_0;
        end if; 
    end process;

    or_ln139_1_fu_330_p2 <= (ap_phi_mux_j_phi_fu_148_p4 or ap_const_lv32_2);
    or_ln139_2_fu_341_p2 <= (ap_phi_mux_j_phi_fu_148_p4 or ap_const_lv32_3);
    or_ln139_fu_319_p2 <= (ap_phi_mux_j_phi_fu_148_p4 or ap_const_lv32_1);
    p_Result_10_fu_403_p5 <= (ap_phi_reg_pp0_iter0_val_V_14_reg_165(63 downto 48) & ap_const_lv16_0 & ap_phi_reg_pp0_iter0_val_V_14_reg_165(31 downto 0));
    p_Result_11_fu_446_p5 <= (nms_mat_410_dout & ap_phi_reg_pp0_iter1_val_V_15_reg_174(47 downto 0));
    p_Result_12_fu_433_p5 <= (ap_const_lv16_0 & ap_phi_reg_pp0_iter1_val_V_15_reg_174(47 downto 0));
    p_Result_6_fu_367_p5 <= (val_V_fu_104(63 downto 16) & nms_mat_410_dout);
    p_Result_7_fu_391_p5 <= (ap_phi_reg_pp0_iter0_val_V_13_reg_156(63 downto 32) & nms_mat_410_dout & ap_phi_reg_pp0_iter0_val_V_13_reg_156(15 downto 0));
    p_Result_8_fu_379_p5 <= (ap_phi_reg_pp0_iter0_val_V_13_reg_156(63 downto 32) & ap_const_lv16_0 & ap_phi_reg_pp0_iter0_val_V_13_reg_156(15 downto 0));
    p_Result_9_fu_415_p5 <= (ap_phi_reg_pp0_iter0_val_V_14_reg_165(63 downto 48) & nms_mat_410_dout & ap_phi_reg_pp0_iter0_val_V_14_reg_165(31 downto 0));
    p_Result_s_fu_355_p5 <= (val_V_fu_104(63 downto 16) & ap_const_lv16_0);
    tmp_20_fu_287_p4 <= add_ln129_fu_282_p2(9 downto 2);
    tmp_21_fu_297_p3 <= (tmp_20_fu_287_p4 & ap_const_lv2_0);
    tmp_fu_197_p4 <= imgwidth_dout(10 downto 5);
    tmp_s_fu_245_p4 <= add_ln111_fu_225_p2(11 downto 3);
    trunc_ln110_fu_193_p1 <= imgwidth_dout(5 - 1 downto 0);
    zext_ln111_1_fu_255_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(col_loop_count_ac_fu_231_p4),9));
    zext_ln111_fu_215_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln_fu_207_p3),12));
    zext_ln116_fu_241_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(col_loop_count_ac_fu_231_p4),32));
    zext_ln117_fu_267_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(col_loop_count_fu_259_p3),10));
    zext_ln129_fu_305_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_21_fu_297_p3),32));
end behav;
