-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
-- Version: 2020.2
-- Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity canny_accel_xFCannyKernel_0_11_0_800_1280_0_13_8_32_2_2_24_24_160_2_480_3_false_Block_split26_proc is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    img_width_dout : IN STD_LOGIC_VECTOR (10 downto 0);
    img_width_empty_n : IN STD_LOGIC;
    img_width_read : OUT STD_LOGIC;
    img_height_dout : IN STD_LOGIC_VECTOR (9 downto 0);
    img_height_empty_n : IN STD_LOGIC;
    img_height_read : OUT STD_LOGIC;
    imgwidth_out_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    imgwidth_out_full_n : IN STD_LOGIC;
    imgwidth_out_write : OUT STD_LOGIC;
    height_out_din : OUT STD_LOGIC_VECTOR (9 downto 0);
    height_out_full_n : IN STD_LOGIC;
    height_out_write : OUT STD_LOGIC;
    imgwidth_2_cast_out_out_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    imgwidth_2_cast_out_out_full_n : IN STD_LOGIC;
    imgwidth_2_cast_out_out_write : OUT STD_LOGIC );
end;


architecture behav of canny_accel_xFCannyKernel_0_11_0_800_1280_0_13_8_32_2_2_24_24_160_2_480_3_false_Block_split26_proc is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal img_width_blk_n : STD_LOGIC;
    signal img_height_blk_n : STD_LOGIC;
    signal imgwidth_out_blk_n : STD_LOGIC;
    signal height_out_blk_n : STD_LOGIC;
    signal imgwidth_2_cast_out_out_blk_n : STD_LOGIC;
    signal ap_block_state1 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((real_start = ap_const_logic_0) or (imgwidth_2_cast_out_out_full_n = ap_const_logic_0) or (height_out_full_n = ap_const_logic_0) or (imgwidth_out_full_n = ap_const_logic_0) or (img_height_empty_n = ap_const_logic_0) or (img_width_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((real_start = ap_const_logic_1) and (internal_ap_ready = ap_const_logic_0))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, img_width_empty_n, img_height_empty_n, imgwidth_out_full_n, height_out_full_n, imgwidth_2_cast_out_out_full_n)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_block_state1_assign_proc : process(real_start, ap_done_reg, img_width_empty_n, img_height_empty_n, imgwidth_out_full_n, height_out_full_n, imgwidth_2_cast_out_out_full_n)
    begin
                ap_block_state1 <= ((real_start = ap_const_logic_0) or (imgwidth_2_cast_out_out_full_n = ap_const_logic_0) or (height_out_full_n = ap_const_logic_0) or (imgwidth_out_full_n = ap_const_logic_0) or (img_height_empty_n = ap_const_logic_0) or (img_width_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, img_width_empty_n, img_height_empty_n, imgwidth_out_full_n, height_out_full_n, imgwidth_2_cast_out_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (imgwidth_2_cast_out_out_full_n = ap_const_logic_0) or (height_out_full_n = ap_const_logic_0) or (imgwidth_out_full_n = ap_const_logic_0) or (img_height_empty_n = ap_const_logic_0) or (img_width_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;

    height_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, height_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            height_out_blk_n <= height_out_full_n;
        else 
            height_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    height_out_din <= img_height_dout;

    height_out_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, img_width_empty_n, img_height_empty_n, imgwidth_out_full_n, height_out_full_n, imgwidth_2_cast_out_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (imgwidth_2_cast_out_out_full_n = ap_const_logic_0) or (height_out_full_n = ap_const_logic_0) or (imgwidth_out_full_n = ap_const_logic_0) or (img_height_empty_n = ap_const_logic_0) or (img_width_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            height_out_write <= ap_const_logic_1;
        else 
            height_out_write <= ap_const_logic_0;
        end if; 
    end process;


    img_height_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, img_height_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            img_height_blk_n <= img_height_empty_n;
        else 
            img_height_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    img_height_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, img_width_empty_n, img_height_empty_n, imgwidth_out_full_n, height_out_full_n, imgwidth_2_cast_out_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (imgwidth_2_cast_out_out_full_n = ap_const_logic_0) or (height_out_full_n = ap_const_logic_0) or (imgwidth_out_full_n = ap_const_logic_0) or (img_height_empty_n = ap_const_logic_0) or (img_width_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            img_height_read <= ap_const_logic_1;
        else 
            img_height_read <= ap_const_logic_0;
        end if; 
    end process;


    img_width_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, img_width_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            img_width_blk_n <= img_width_empty_n;
        else 
            img_width_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    img_width_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, img_width_empty_n, img_height_empty_n, imgwidth_out_full_n, height_out_full_n, imgwidth_2_cast_out_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (imgwidth_2_cast_out_out_full_n = ap_const_logic_0) or (height_out_full_n = ap_const_logic_0) or (imgwidth_out_full_n = ap_const_logic_0) or (img_height_empty_n = ap_const_logic_0) or (img_width_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            img_width_read <= ap_const_logic_1;
        else 
            img_width_read <= ap_const_logic_0;
        end if; 
    end process;


    imgwidth_2_cast_out_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, imgwidth_2_cast_out_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            imgwidth_2_cast_out_out_blk_n <= imgwidth_2_cast_out_out_full_n;
        else 
            imgwidth_2_cast_out_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    imgwidth_2_cast_out_out_din <= img_width_dout(10 downto 3);

    imgwidth_2_cast_out_out_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, img_width_empty_n, img_height_empty_n, imgwidth_out_full_n, height_out_full_n, imgwidth_2_cast_out_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (imgwidth_2_cast_out_out_full_n = ap_const_logic_0) or (height_out_full_n = ap_const_logic_0) or (imgwidth_out_full_n = ap_const_logic_0) or (img_height_empty_n = ap_const_logic_0) or (img_width_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            imgwidth_2_cast_out_out_write <= ap_const_logic_1;
        else 
            imgwidth_2_cast_out_out_write <= ap_const_logic_0;
        end if; 
    end process;


    imgwidth_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, imgwidth_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            imgwidth_out_blk_n <= imgwidth_out_full_n;
        else 
            imgwidth_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    imgwidth_out_din <= img_width_dout(10 downto 3);

    imgwidth_out_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, img_width_empty_n, img_height_empty_n, imgwidth_out_full_n, height_out_full_n, imgwidth_2_cast_out_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (imgwidth_2_cast_out_out_full_n = ap_const_logic_0) or (height_out_full_n = ap_const_logic_0) or (imgwidth_out_full_n = ap_const_logic_0) or (img_height_empty_n = ap_const_logic_0) or (img_width_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            imgwidth_out_write <= ap_const_logic_1;
        else 
            imgwidth_out_write <= ap_const_logic_0;
        end if; 
    end process;


    internal_ap_ready_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, img_width_empty_n, img_height_empty_n, imgwidth_out_full_n, height_out_full_n, imgwidth_2_cast_out_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (imgwidth_2_cast_out_out_full_n = ap_const_logic_0) or (height_out_full_n = ap_const_logic_0) or (imgwidth_out_full_n = ap_const_logic_0) or (img_height_empty_n = ap_const_logic_0) or (img_width_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_full_n = ap_const_logic_0) and (start_once_reg = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((real_start = ap_const_logic_1) and (start_once_reg = ap_const_logic_0))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
