// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module canny_accel_Mat2AxiStream (
        dst_mat_422_dout,
        dst_mat_422_empty_n,
        dst_mat_422_read,
        ldata1_din,
        ldata1_full_n,
        ldata1_write,
        rows_dout,
        rows_empty_n,
        rows_read,
        cols_dout,
        cols_empty_n,
        cols_read,
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input  [63:0] dst_mat_422_dout;
input   dst_mat_422_empty_n;
output   dst_mat_422_read;
output  [63:0] ldata1_din;
input   ldata1_full_n;
output   ldata1_write;
input  [15:0] rows_dout;
input   rows_empty_n;
output   rows_read;
input  [10:0] cols_dout;
input   cols_empty_n;
output   cols_read;
input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    cols_npc_aligned63_U0_ap_start;
wire    cols_npc_aligned63_U0_ap_done;
wire    cols_npc_aligned63_U0_ap_continue;
wire    cols_npc_aligned63_U0_ap_idle;
wire    cols_npc_aligned63_U0_ap_ready;
wire    cols_npc_aligned63_U0_start_out;
wire    cols_npc_aligned63_U0_start_write;
wire    cols_npc_aligned63_U0_cols_read;
wire    cols_npc_aligned63_U0_rows_read;
wire   [10:0] cols_npc_aligned63_U0_cols_out_din;
wire    cols_npc_aligned63_U0_cols_out_write;
wire   [15:0] cols_npc_aligned63_U0_rows_out_din;
wire    cols_npc_aligned63_U0_rows_out_write;
wire   [6:0] cols_npc_aligned63_U0_ret_out_din;
wire    cols_npc_aligned63_U0_ret_out_write;
wire    last_blk_pxl_width_U0_ap_start;
wire    last_blk_pxl_width_U0_ap_done;
wire    last_blk_pxl_width_U0_ap_continue;
wire    last_blk_pxl_width_U0_ap_idle;
wire    last_blk_pxl_width_U0_ap_ready;
wire   [6:0] last_blk_pxl_width_U0_return_r;
wire    last_blk_pxl_width_U0_return_r_ap_vld;
wire    last_blk_pxl_width_U0_cols_read;
wire    last_blk_pxl_width_U0_cols_bound_per_npc_read;
wire   [6:0] last_blk_pxl_width_U0_cols_bound_per_npc_out_din;
wire    last_blk_pxl_width_U0_cols_bound_per_npc_out_write;
wire    ap_channel_done_p_channel;
wire    p_channel_full_n;
wire    MatStream2AxiStream_2_U0_ap_start;
wire    MatStream2AxiStream_2_U0_ap_done;
wire    MatStream2AxiStream_2_U0_ap_continue;
wire    MatStream2AxiStream_2_U0_ap_idle;
wire    MatStream2AxiStream_2_U0_ap_ready;
wire    MatStream2AxiStream_2_U0_dst_mat_422_read;
wire   [63:0] MatStream2AxiStream_2_U0_ldata1_din;
wire    MatStream2AxiStream_2_U0_ldata1_write;
wire    MatStream2AxiStream_2_U0_rows_read;
wire    MatStream2AxiStream_2_U0_cols_bound_per_npc_read;
wire    ap_sync_continue;
wire    cols_c_i_full_n;
wire   [10:0] cols_c_i_dout;
wire    cols_c_i_empty_n;
wire    rows_c_i_full_n;
wire   [15:0] rows_c_i_dout;
wire    rows_c_i_empty_n;
wire    p_c_i_full_n;
wire   [6:0] p_c_i_dout;
wire    p_c_i_empty_n;
wire   [6:0] p_channel_dout;
wire    p_channel_empty_n;
wire    p_c11_i_full_n;
wire   [6:0] p_c11_i_dout;
wire    p_c11_i_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
wire   [0:0] start_for_last_blk_pxl_width_U0_din;
wire    start_for_last_blk_pxl_width_U0_full_n;
wire   [0:0] start_for_last_blk_pxl_width_U0_dout;
wire    start_for_last_blk_pxl_width_U0_empty_n;
wire    last_blk_pxl_width_U0_start_full_n;
wire    last_blk_pxl_width_U0_start_write;
wire    MatStream2AxiStream_2_U0_start_full_n;
wire    MatStream2AxiStream_2_U0_start_write;

canny_accel_cols_npc_aligned63 cols_npc_aligned63_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(cols_npc_aligned63_U0_ap_start),
    .start_full_n(start_for_last_blk_pxl_width_U0_full_n),
    .ap_done(cols_npc_aligned63_U0_ap_done),
    .ap_continue(cols_npc_aligned63_U0_ap_continue),
    .ap_idle(cols_npc_aligned63_U0_ap_idle),
    .ap_ready(cols_npc_aligned63_U0_ap_ready),
    .start_out(cols_npc_aligned63_U0_start_out),
    .start_write(cols_npc_aligned63_U0_start_write),
    .cols_dout(cols_dout),
    .cols_empty_n(cols_empty_n),
    .cols_read(cols_npc_aligned63_U0_cols_read),
    .rows_dout(rows_dout),
    .rows_empty_n(rows_empty_n),
    .rows_read(cols_npc_aligned63_U0_rows_read),
    .cols_out_din(cols_npc_aligned63_U0_cols_out_din),
    .cols_out_full_n(cols_c_i_full_n),
    .cols_out_write(cols_npc_aligned63_U0_cols_out_write),
    .rows_out_din(cols_npc_aligned63_U0_rows_out_din),
    .rows_out_full_n(rows_c_i_full_n),
    .rows_out_write(cols_npc_aligned63_U0_rows_out_write),
    .ret_out_din(cols_npc_aligned63_U0_ret_out_din),
    .ret_out_full_n(p_c_i_full_n),
    .ret_out_write(cols_npc_aligned63_U0_ret_out_write)
);

canny_accel_last_blk_pxl_width last_blk_pxl_width_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(last_blk_pxl_width_U0_ap_start),
    .ap_done(last_blk_pxl_width_U0_ap_done),
    .ap_continue(last_blk_pxl_width_U0_ap_continue),
    .ap_idle(last_blk_pxl_width_U0_ap_idle),
    .ap_ready(last_blk_pxl_width_U0_ap_ready),
    .return_r(last_blk_pxl_width_U0_return_r),
    .return_r_ap_vld(last_blk_pxl_width_U0_return_r_ap_vld),
    .cols_dout(cols_c_i_dout),
    .cols_empty_n(cols_c_i_empty_n),
    .cols_read(last_blk_pxl_width_U0_cols_read),
    .cols_bound_per_npc_dout(p_c_i_dout),
    .cols_bound_per_npc_empty_n(p_c_i_empty_n),
    .cols_bound_per_npc_read(last_blk_pxl_width_U0_cols_bound_per_npc_read),
    .cols_bound_per_npc_out_din(last_blk_pxl_width_U0_cols_bound_per_npc_out_din),
    .cols_bound_per_npc_out_full_n(p_c11_i_full_n),
    .cols_bound_per_npc_out_write(last_blk_pxl_width_U0_cols_bound_per_npc_out_write)
);

canny_accel_MatStream2AxiStream_2_s MatStream2AxiStream_2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(MatStream2AxiStream_2_U0_ap_start),
    .ap_done(MatStream2AxiStream_2_U0_ap_done),
    .ap_continue(MatStream2AxiStream_2_U0_ap_continue),
    .ap_idle(MatStream2AxiStream_2_U0_ap_idle),
    .ap_ready(MatStream2AxiStream_2_U0_ap_ready),
    .dst_mat_422_dout(dst_mat_422_dout),
    .dst_mat_422_empty_n(dst_mat_422_empty_n),
    .dst_mat_422_read(MatStream2AxiStream_2_U0_dst_mat_422_read),
    .ldata1_din(MatStream2AxiStream_2_U0_ldata1_din),
    .ldata1_full_n(ldata1_full_n),
    .ldata1_write(MatStream2AxiStream_2_U0_ldata1_write),
    .rows_dout(rows_c_i_dout),
    .rows_empty_n(rows_c_i_empty_n),
    .rows_read(MatStream2AxiStream_2_U0_rows_read),
    .cols_bound_per_npc_dout(p_c11_i_dout),
    .cols_bound_per_npc_empty_n(p_c11_i_empty_n),
    .cols_bound_per_npc_read(MatStream2AxiStream_2_U0_cols_bound_per_npc_read),
    .last_blk_width(p_channel_dout)
);

canny_accel_fifo_w11_d2_S_x cols_c_i_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(cols_npc_aligned63_U0_cols_out_din),
    .if_full_n(cols_c_i_full_n),
    .if_write(cols_npc_aligned63_U0_cols_out_write),
    .if_dout(cols_c_i_dout),
    .if_empty_n(cols_c_i_empty_n),
    .if_read(last_blk_pxl_width_U0_cols_read)
);

canny_accel_fifo_w16_d3_S rows_c_i_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(cols_npc_aligned63_U0_rows_out_din),
    .if_full_n(rows_c_i_full_n),
    .if_write(cols_npc_aligned63_U0_rows_out_write),
    .if_dout(rows_c_i_dout),
    .if_empty_n(rows_c_i_empty_n),
    .if_read(MatStream2AxiStream_2_U0_rows_read)
);

canny_accel_fifo_w7_d2_S_x p_c_i_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(cols_npc_aligned63_U0_ret_out_din),
    .if_full_n(p_c_i_full_n),
    .if_write(cols_npc_aligned63_U0_ret_out_write),
    .if_dout(p_c_i_dout),
    .if_empty_n(p_c_i_empty_n),
    .if_read(last_blk_pxl_width_U0_cols_bound_per_npc_read)
);

canny_accel_fifo_w7_d2_S_x p_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(last_blk_pxl_width_U0_return_r),
    .if_full_n(p_channel_full_n),
    .if_write(last_blk_pxl_width_U0_ap_done),
    .if_dout(p_channel_dout),
    .if_empty_n(p_channel_empty_n),
    .if_read(MatStream2AxiStream_2_U0_ap_ready)
);

canny_accel_fifo_w7_d2_S_x p_c11_i_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(last_blk_pxl_width_U0_cols_bound_per_npc_out_din),
    .if_full_n(p_c11_i_full_n),
    .if_write(last_blk_pxl_width_U0_cols_bound_per_npc_out_write),
    .if_dout(p_c11_i_dout),
    .if_empty_n(p_c11_i_empty_n),
    .if_read(MatStream2AxiStream_2_U0_cols_bound_per_npc_read)
);

canny_accel_start_for_last_blk_pxl_width_U0 start_for_last_blk_pxl_width_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_last_blk_pxl_width_U0_din),
    .if_full_n(start_for_last_blk_pxl_width_U0_full_n),
    .if_write(cols_npc_aligned63_U0_start_write),
    .if_dout(start_for_last_blk_pxl_width_U0_dout),
    .if_empty_n(start_for_last_blk_pxl_width_U0_empty_n),
    .if_read(last_blk_pxl_width_U0_ap_ready)
);

assign MatStream2AxiStream_2_U0_ap_continue = ap_continue;

assign MatStream2AxiStream_2_U0_ap_start = p_channel_empty_n;

assign MatStream2AxiStream_2_U0_start_full_n = 1'b1;

assign MatStream2AxiStream_2_U0_start_write = 1'b0;

assign ap_channel_done_p_channel = last_blk_pxl_width_U0_ap_done;

assign ap_done = MatStream2AxiStream_2_U0_ap_done;

assign ap_idle = (last_blk_pxl_width_U0_ap_idle & (p_channel_empty_n ^ 1'b1) & cols_npc_aligned63_U0_ap_idle & MatStream2AxiStream_2_U0_ap_idle);

assign ap_ready = cols_npc_aligned63_U0_ap_ready;

assign ap_sync_continue = ap_continue;

assign ap_sync_done = MatStream2AxiStream_2_U0_ap_done;

assign ap_sync_ready = cols_npc_aligned63_U0_ap_ready;

assign cols_npc_aligned63_U0_ap_continue = 1'b1;

assign cols_npc_aligned63_U0_ap_start = ap_start;

assign cols_read = cols_npc_aligned63_U0_cols_read;

assign dst_mat_422_read = MatStream2AxiStream_2_U0_dst_mat_422_read;

assign last_blk_pxl_width_U0_ap_continue = p_channel_full_n;

assign last_blk_pxl_width_U0_ap_start = start_for_last_blk_pxl_width_U0_empty_n;

assign last_blk_pxl_width_U0_start_full_n = 1'b1;

assign last_blk_pxl_width_U0_start_write = 1'b0;

assign ldata1_din = MatStream2AxiStream_2_U0_ldata1_din;

assign ldata1_write = MatStream2AxiStream_2_U0_ldata1_write;

assign rows_read = cols_npc_aligned63_U0_rows_read;

assign start_for_last_blk_pxl_width_U0_din = 1'b1;

endmodule //canny_accel_Mat2AxiStream
