#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : system.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Wed Dec 18 11:27:20 +0800 2024
# SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved. 
#
# usage: system.sh [-help]
# usage: system.sh [-lib_map_path]
# usage: system.sh [-noclean_files]
# usage: system.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'system.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xpm lib_cdc_v1_0_2 lib_pkg_v1_0_2 fifo_generator_v13_2_5 lib_fifo_v1_0_14 blk_mem_gen_v8_4_4 lib_bmg_v1_0_13 lib_srl_fifo_v1_0_2 axi_datamover_v5_1_24 axi_vdma_v6_3_10 xil_defaultlib proc_sys_reset_v5_0_13 v_vid_in_axi4s_v4_0_9 axi_infrastructure_v1_1_0 axi_vip_v1_1_8 zynq_ultra_ps_e_vip_v1_0_8 xlconstant_v1_1_7 smartconnect_v1_0 axi_register_slice_v2_1_22 generic_baseblocks_v2_1_0 axi_data_fifo_v2_1_21 axi_crossbar_v2_1_23 axi_protocol_converter_v2_1_22)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "system.sh - Script generated by export_simulation (Vivado v2020.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "D:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "D:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "D:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "D:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "D:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "D:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "D:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "D:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "D:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "D:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "D:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "D:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "D:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/276e/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_5 $vhdlan_opts \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/276e/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/276e/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_fifo_v1_0_14 $vhdlan_opts \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/a5cb/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_4_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/2985/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_bmg_v1_0_13 $vhdlan_opts \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/af67/hdl/lib_bmg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_24 $vhdlan_opts \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/4ab6/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_vdma_v6_3_10 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/7860/hdl/axi_vdma_v6_3_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_vdma_v6_3_10 $vhdlan_opts \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/7860/hdl/axi_vdma_v6_3_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_axi_vdma_0_0/sim/system_axi_vdma_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_clk_wiz.v" \
    "$ref_dir/../../../bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.v" \
    "$ref_dir/../../../bd/system/ipshared/8797/src/ov5640_capture_data.v" \
    "$ref_dir/../../../bd/system/ip/system_ov5640_capture_data_0_0/sim/system_ov5640_capture_data_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_rst_ps8_0_99M_0/sim/system_rst_ps8_0_99M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work v_vid_in_axi4s_v4_0_9 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/b2aa/hdl/v_vid_in_axi4s_v4_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_v_vid_in_axi4s_0_0/sim/system_v_vid_in_axi4s_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_8 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/94c3/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work zynq_ultra_ps_e_vip_v1_0_8 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/da1e/hdl/zynq_ultra_ps_e_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_zynq_ultra_ps_e_0_0/sim/system_zynq_ultra_ps_e_0_0_vip_wrapper.v" \
    "$ref_dir/../../../bd/system/ip/system_ov5640_capture_data_0_1/sim/system_ov5640_capture_data_0_1.v" \
    "$ref_dir/../../../bd/system/ip/system_v_vid_in_axi4s_0_2/sim/system_v_vid_in_axi4s_0_2.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_axi_vdma_0_1/sim/system_axi_vdma_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_video_image_process_0_0/src/blk_mem_gen_0/sim/blk_mem_gen_0.v" \
    "$ref_dir/../../../bd/system/ipshared/4690/src/Sort3.v" \
    "$ref_dir/../../../bd/system/ipshared/4690/src/VIP_matrix_generate_3x3_8bit.v" \
    "$ref_dir/../../../bd/system/ipshared/4690/src/gray_median_filter.v" \
    "$ref_dir/../../../bd/system/ipshared/4690/src/line_shift_RAM_8bit.v" \
    "$ref_dir/../../../bd/system/ipshared/4690/src/median_3x3.v" \
    "$ref_dir/../../../bd/system/ipshared/4690/src/rgb2ycbcr.v" \
    "$ref_dir/../../../bd/system/ipshared/4690/src/Video_Image_Processor.v" \
    "$ref_dir/../../../bd/system/ip/system_video_image_process_0_0/sim/system_video_image_process_0_0.v" \
    "$ref_dir/../../../bd/system/ip/system_video_image_process_0_1/sim/system_video_image_process_0_1.v" \
    "$ref_dir/../../../bd/system/ip/system_ov5640_capture_data_1_0/sim/system_ov5640_capture_data_1_0.v" \
    "$ref_dir/../../../bd/system/ip/system_video_image_process_1_0/sim/system_video_image_process_1_0.v" \
    "$ref_dir/../../../bd/system/ip/system_v_vid_in_axi4s_1_0/sim/system_v_vid_in_axi4s_1_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_axi_vdma_1_2/sim/system_axi_vdma_1_2.vhd" \
    "$ref_dir/../../../bd/system/ip/system_rst_ps8_0_149M_0/sim/system_rst_ps8_0_149M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_addrbound.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_Array2xfMat_64_0_800_1280_8_2_s.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_Axi2AxiStream.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_Axi2Mat.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_AxiStream2Axi.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_AxiStream2Mat.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_AxiStream2MatStream_2_s.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_Block_split11_proc72.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_Canny_3_0_0_11_800_1280_8_32_false_2_2_s.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_cols_npc_aligned47.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_cols_npc_aligned63.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_control_s_axi.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_fifo_w7_d2_S.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_fifo_w7_d2_S_x.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_fifo_w8_d4_S.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_fifo_w8_d6_S.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_fifo_w10_d2_S.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_fifo_w10_d3_S.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_fifo_w10_d4_S.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_fifo_w11_d2_S.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_fifo_w11_d2_S_x.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_fifo_w11_d2_S_x0.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_fifo_w11_d3_S.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_fifo_w11_d4_S.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_fifo_w16_d2_S.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_fifo_w16_d2_S_x.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_fifo_w16_d3_S.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_fifo_w29_d2_S.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_fifo_w32_d2_S.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_fifo_w32_d2_S_x.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_fifo_w32_d2_S_x0.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_fifo_w32_d3_S.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_fifo_w32_d3_S_x.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_fifo_w32_d4_S.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_fifo_w64_d2_S.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_fifo_w64_d2_S_x.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_fifo_w64_d2_S_x0.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_fifo_w64_d2_S_x1.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_fifo_w64_d4_S.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_fifo_w64_d4_S_x.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_fifo_w64_d480_A.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_fifo_w128_d2_S.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_gmem1_m_axi.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_gmem2_m_axi.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_hls_deadlock_detection_unit.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_last_blk_pxl_width.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_last_blk_pxl_width_1.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_Mat2Axi.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_Mat2Axi_Block_split13_proc.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_Mat2Axi_entry67.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_Mat2AxiStream.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_MatStream2AxiStream_2_s.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_mul_32s_29s_32_1_1.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_mul_mul_16ns_7ns_23_4_1.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_mul_mul_16ns_11ns_27_3_1.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_mul_mul_16ns_15ns_30_4_1.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_mul_mul_16ns_16ns_32_3_1.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_mux_32_13_1_1.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_mux_32_64_1_1.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_mux_32_128_1_1.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_start_for_addrbound_U0.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_start_for_AxiStream2Mat_U0.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_start_for_Canny_3_0_0_11_800_1280_8_32_false_2_2_U0.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_start_for_last_blk_pxl_width_1_U0.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_start_for_last_blk_pxl_width_U0.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_start_for_Mat2AxiStream_U0.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_start_for_xFAngleKernel_3_0_800_1280_4_0_8_2_2_32_24_160_480_U0.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_start_for_xFAverageGaussianMask3x3_0_0_800_1280_0_8_2_2_24_160_U0.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_start_for_xFCannyKernel_0_11_0_800_1280_0_13_8_32_2_2_24_24_160_2_480_3_falsebkb.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_start_for_xFDuplicate_rows_3_800_1280_4_8_2_2_2_2_2_2_32_160_U0.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_start_for_xFMagnitudeKernel_3_3_800_1280_4_4_8_2_2_2_32_32_160_U0.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_start_for_xfMat2Array_64_11_800_1280_32_2_1_U0.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_start_for_xFPackNMS_11_11_800_1280_13_13_8_32_2_2_6_24_U0.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_start_for_xFSobel_0_3_800_1280_0_4_8_2_2_2_24_32_3_false_U0.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_start_for_xFSuppression3x3_3_0_11_800_1280_4_0_13_8_2_32_24_6_160_480_2_U0.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_xFAngleKernel_3_0_800_1280_4_0_8_2_2_32_24_160_480_s.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_xFAverageGaussianMask3x3_0_0_800_1280_0_8_2_2_24_160_s.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_xFAverageGaussianMask3x3_0_0_800_1280_0_8_2_2_24_160_s_buf_V_0.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_xFCannyKernel_0_11_0_800_1280_0_13_8_32_2_2_24_24_160_2_480_3_false_Block_split26_proc.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_xFCannyKernel_0_11_0_800_1280_0_13_8_32_2_2_24_24_160_2_480_3_false_entry53.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_xFCannyKernel_0_11_0_800_1280_0_13_8_32_2_2_24_24_160_2_480_3_false_s.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_xFDuplicate_rows_3_800_1280_4_8_2_2_2_2_2_2_32_160_s.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_xfExtractPixels_8_24_0_1.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_xfExtractPixels_8_24_0_s.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_xfExtractPixels_8_32_4_s.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_xFFindmax3x3_4_0_13_s.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_xFMagnitudeKernel_3_3_800_1280_4_4_8_2_2_2_32_32_160_s.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_xfMat2Array_64_11_800_1280_32_2_1_s.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_xFPackNMS_11_11_800_1280_13_13_8_32_2_2_6_24_s.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_xFSobel3x3_0_3_800_1280_0_4_8_2_2_2_24_32_161_3_9_false_s.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_xFSobel_0_3_800_1280_0_4_8_2_2_2_24_32_3_false_s.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_xFSuppression3x3_3_0_11_800_1280_4_0_13_8_2_32_24_6_160_480_2_s.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_xFSuppression3x3_3_0_11_800_1280_4_0_13_8_2_32_24_6_160_480_2_s_angle_V_0.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel_xFSuppression3x3_3_0_11_800_1280_4_0_13_8_2_32_24_6_160_480_2_s_buf_V_0.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog/canny_accel.v" \
    "$ref_dir/../../../bd/system/ip/system_canny_accel_0_0/sim/system_canny_accel_0_0.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/b717/hdl/verilog/edgetracing_accel_control_s_axi.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/b717/hdl/verilog/edgetracing_accel_gmem3_m_axi.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/b717/hdl/verilog/edgetracing_accel_gmem4_m_axi.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/b717/hdl/verilog/edgetracing_accel_iBuff_V_0.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/b717/hdl/verilog/edgetracing_accel_iBuff_V_2.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/b717/hdl/verilog/edgetracing_accel_mac_muladd_2ns_8ns_24ns_24_4_1.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/b717/hdl/verilog/edgetracing_accel_mul_8ns_3ns_11_1_1.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/b717/hdl/verilog/edgetracing_accel_mul_mul_6ns_11ns_17_4_1.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/b717/hdl/verilog/edgetracing_accel_mul_mul_10ns_6ns_15_4_1.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/b717/hdl/verilog/edgetracing_accel_mul_mul_10ns_8ns_17_4_1.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/b717/hdl/verilog/edgetracing_accel_mul_mul_12s_6ns_18_4_1.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/b717/hdl/verilog/edgetracing_accel_mul_mul_13ns_11ns_24_4_1.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/b717/hdl/verilog/edgetracing_accel_mul_mul_23ns_6ns_29_4_1.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/b717/hdl/verilog/edgetracing_accel_mul_mul_24s_6ns_30_4_1.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/b717/hdl/verilog/edgetracing_accel_mux_114_64_1_1.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/b717/hdl/verilog/edgetracing_accel_mux_164_64_1_1.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/b717/hdl/verilog/edgetracing_accel_oBuff_V.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/b717/hdl/verilog/edgetracing_accel_PixelProcessNew_1_s.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/b717/hdl/verilog/edgetracing_accel_TopDown_11_3_1024_s.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/b717/hdl/verilog/edgetracing_accel_udiv_11s_6ns_11_15_seq_1.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/b717/hdl/verilog/edgetracing_accel_udiv_12ns_11ns_12_16_seq_1.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/b717/hdl/verilog/edgetracing_accel_urem_13ns_3ns_13_17_seq_1.v" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/b717/hdl/verilog/edgetracing_accel.v" \
    "$ref_dir/../../../bd/system/ip/system_edgetracing_accel_0_0/sim/system_edgetracing_accel_0_0.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/sim/bd_4223.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/fcfc/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_0/sim/bd_4223_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_1/sim/bd_4223_psr0_0.vhd" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_2/sim/bd_4223_psr_aclk_0.vhd" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_3/sim/bd_4223_psr_aclk1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/25b7/hdl/sc_util_v1_0_vl_rfs.sv" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/c012/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_4/sim/bd_4223_arsw_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_5/sim/bd_4223_rsw_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_6/sim/bd_4223_awsw_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_7/sim/bd_4223_wsw_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_8/sim/bd_4223_bsw_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/ea34/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_9/sim/bd_4223_s00mmu_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/4fd2/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_10/sim/bd_4223_s00tr_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/8047/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_11/sim/bd_4223_s00sic_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/b89e/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_12/sim/bd_4223_s00a2s_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/896c/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_13/sim/bd_4223_sawn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_14/sim/bd_4223_swn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_15/sim/bd_4223_sbn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_16/sim/bd_4223_s01mmu_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_17/sim/bd_4223_s01tr_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_18/sim/bd_4223_s01sic_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_19/sim/bd_4223_s01a2s_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_20/sim/bd_4223_sawn_1.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_21/sim/bd_4223_swn_1.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_22/sim/bd_4223_sbn_1.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_23/sim/bd_4223_s02mmu_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_24/sim/bd_4223_s02tr_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_25/sim/bd_4223_s02sic_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_26/sim/bd_4223_s02a2s_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_27/sim/bd_4223_sawn_2.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_28/sim/bd_4223_swn_2.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_29/sim/bd_4223_sbn_2.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_30/sim/bd_4223_s04mmu_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_31/sim/bd_4223_s04tr_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_32/sim/bd_4223_s04sic_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_33/sim/bd_4223_s04a2s_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_34/sim/bd_4223_sarn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_35/sim/bd_4223_srn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_36/sim/bd_4223_sawn_3.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_37/sim/bd_4223_swn_3.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_38/sim/bd_4223_sbn_3.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_39/sim/bd_4223_s05mmu_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_40/sim/bd_4223_s05tr_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_41/sim/bd_4223_s05sic_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_42/sim/bd_4223_s05a2s_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_43/sim/bd_4223_sarn_1.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_44/sim/bd_4223_srn_1.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_45/sim/bd_4223_sawn_4.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_46/sim/bd_4223_swn_4.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_47/sim/bd_4223_sbn_4.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_48/sim/bd_4223_s06mmu_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_49/sim/bd_4223_s06tr_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_50/sim/bd_4223_s06sic_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_51/sim/bd_4223_s06a2s_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_52/sim/bd_4223_sarn_2.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_53/sim/bd_4223_srn_2.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_54/sim/bd_4223_sawn_5.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_55/sim/bd_4223_swn_5.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_56/sim/bd_4223_sbn_5.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_57/sim/bd_4223_s07mmu_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_58/sim/bd_4223_s07tr_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_59/sim/bd_4223_s07sic_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_60/sim/bd_4223_s07a2s_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_61/sim/bd_4223_sarn_3.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_62/sim/bd_4223_srn_3.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_63/sim/bd_4223_sawn_6.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_64/sim/bd_4223_swn_6.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_65/sim/bd_4223_sbn_6.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/7005/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_66/sim/bd_4223_m00s2a_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_67/sim/bd_4223_m00arn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_68/sim/bd_4223_m00rn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_69/sim/bd_4223_m00awn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_70/sim/bd_4223_m00wn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_71/sim/bd_4223_m00bn_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/7bd7/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/bd_0/ip/ip_72/sim/bd_4223_m00e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/af2c/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_9/sim/system_axi_smc_9.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_21 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/54c0/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_23 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/bc0a/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_xbar_9/sim/system_xbar_9.v" \
    "$ref_dir/../../../bd/system/sim/system.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/5cee/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/9626/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../thr_hls_compact_1280_800.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_auto_pc_0/sim/system_auto_pc_0.v" \
    "$ref_dir/../../../bd/system/ipshared/f32a/hdl/count.v" \
    "$ref_dir/../../../bd/system/ipshared/f32a/hdl/count_ip_v1_0_S00_AXI.v" \
    "$ref_dir/../../../bd/system/ipshared/f32a/hdl/count_ip_v1_0.v" \
    "$ref_dir/../../../bd/system/ip/system_count_ip_0_1/sim/system_count_ip_0_1.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.system xil_defaultlib.glbl -o system_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./system_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./system.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key system_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc system_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./system.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: system.sh [-help]\n\
Usage: system.sh [-lib_map_path]\n\
Usage: system.sh [-reset_run]\n\
Usage: system.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
